name: Build and Push Docker Image to Docker Hub and ECR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Replace with your desired AWS region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generate timestamp
        id: generate_timestamp
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t kenya-claims-fhir-ig:latest .

      - name: Tag Docker image for Docker Hub
        run: |
          docker tag kenya-claims-fhir-ig:latest intellisoftkenya/kenya-claims-fhir-ig:${{ env.TIMESTAMP }}
          docker tag kenya-claims-fhir-ig:latest intellisoftkenya/kenya-claims-fhir-ig:latest

      - name: Tag Docker image for ECR
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/intellisoft"
          docker tag kenya-claims-fhir-ig:latest 813389018368.dkr.ecr.us-east-1.amazonaws.com/intellisoft:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push intellisoftkenya/kenya-claims-fhir-ig:${{ env.TIMESTAMP }}
          docker push intellisoftkenya/kenya-claims-fhir-ig:latest

      - name: Push Docker image to ECR
        run: |
          docker push 813389018368.dkr.ecr.us-east-1.amazonaws.com/intellisoft:latest
